name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build GDLDE
      run: ./mvnw clean verify
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: GDL Workbench (Windows)
        path: product/target/products/gdlde.product-win32.win32.x86_64.zip
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: GDL Workbench (macOS)
        path: product/target/products/gdlde.product-macosx.cocoa.x86_64.zip
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: GDL Workbench (Linux)
        path: product/target/products/gdlde.product-linux.gtk.x86_64.zip
    - name: Upload Release Assets
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: product/target/products/gdlde.product-*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
